name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:

  build:

    name: Test & Coverage 

    runs-on: ubuntu-latest

    env:
      DOTNET_ROLL_FORWARD: Major

    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0
        
    - name: Build project
      run: dotnet build GenHTTP.slnx -c Release

